### ISSUE TITLE
NullPointerException in OAuth2SecurityInterceptor.java:118

### ISSUE THREAD

**Issue by martnst** [wso2/msf4j#341]
Hi, 

I'm experimentally setting up a WOS2 MicroService secured with WSO2 Identity Server based on [this example](https://github.com/wso2/msf4j/tree/v2.0.0/samples/oauth2-security). Doing so I apparently run into an open issue of an unhandled NullPointerException. See [this comment](https://github.com/wso2/msf4j/blob/master/core/src/main/java/org/wso2/msf4j/security/oauth2/OAuth2SecurityInterceptor.java#L115). 

Here is the Stacktrace I get: 

```
2017-01-27 12:12:21 WARN  MSF4JMessageProcessor:83 - Interceptors threw an exception
org.wso2.msf4j.internal.InterceptorException: Exception while executing preCalls
	at org.wso2.msf4j.internal.InterceptorExecutor.execPreCalls(InterceptorExecutor.java:69)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:114)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.wso2.msf4j.security.oauth2.OAuth2SecurityInterceptor.validateToken(OAuth2SecurityInterceptor.java:118)
	at org.wso2.msf4j.security.oauth2.OAuth2SecurityInterceptor.preCall(OAuth2SecurityInterceptor.java:81)
	at org.wso2.msf4j.internal.InterceptorExecutor.execPreCalls(InterceptorExecutor.java:63)
	... 6 more
```

**Do you have any details on what it causing the NPE and how I can fix it in my setup?**

**Comment by martnst** [comment]
Okay, turns out I simply forgot this step: 

`2) Copy resources/introspect.war to wso2is-5.1.0/repository/deployment/server/webapps directory.`

**Comment by thusithathilina** [comment]
Did you able to get this solve?

**Comment by martnst** [comment]
Yes, as commented I forgot to add this introspect module. 

In my opinion, however, there should still be added a more meaning full error message.

**Comment by thusithathilina** [comment]
@martnst Thanks for the info. We will look into this in future. I've marked this as an enhancment
