### ISSUE TITLE
HTTP monitoring sample throws exception when running with java -jar

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/msf4j#489]
**Description:**

HTTP monitoring sample throws the below exception when running with java -jar. This is due to system property not parsed via the command line and is not included in the README.md

```bash
Exception in thread "main" java.lang.RuntimeException: Error loading deployment.yaml Configuration
at org.wso2.msf4j.analytics.httpmonitoring.config.HTTPMonitoringConfigBuilder.build(HTTPMonitoringConfigBuilder.java:60)
at org.wso2.msf4j.analytics.httpmonitoring.HTTPMonitoringInterceptor.<init>(HTTPMonitoringInterceptor.java:55)
at org.wso2.msf4j.sample.httpmonitoring.Application.main(Application.java:34)
Caused by: org.wso2.carbon.config.ConfigurationException: No configuration filepath is provided. configuration provider will not be initialized!
at org.wso2.carbon.config.ConfigProviderFactory.getConfigProvider(ConfigProviderFactory.java:65)
at org.wso2.msf4j.analytics.httpmonitoring.config.HTTPMonitoringConfigBuilder.build(HTTPMonitoringConfigBuilder.java:57)
... 2 more
```

**Suggested Labels:**
Missing documentation

**Affected Product Version:**
Since MSF4J 2.4.0

**Comment by daneshk** [comment]
Closing this issue, since this is addressed in the PR #490
