### ISSUE TITLE
Exception occurred :org/springframework/data/mongodb/repository/MongoRepository

### ISSUE THREAD

**Issue by hoabuiyt** [wso2/msf4j#530]
**Description:**
i have new project https://github.com/hoabuiyt/DemoMongo.git
it using microservices to run with WSO2 MSF4J

run command: **mvn clean install**
![111111111111111111111111](https://user-images.githubusercontent.com/23513544/38477494-16b57d9a-3bdd-11e8-9226-53a345ef71c9.PNG)

and i copy file JAR to folder "D:\wso2-project\wso2ei-6.1.1-update17\wso2\msf4j\deployment\microservices"

and run Carbon.bat from Bin folder

![22222222222222222222222](https://user-images.githubusercontent.com/23513544/38477539-5d283fce-3bdd-11e8-8508-3862a76fd7a5.PNG)

but it wrong when i call API

![333333333](https://user-images.githubusercontent.com/23513544/38477557-76faa216-3bdd-11e8-8bdf-ba41f5521abe.PNG)

please  help me fix it

> [2018-04-09 09:56:08,994]  WARN {org.wso2.msf4j.internal.MSF4JMessageProcessor} - Unmapped exception java.lang.NoClassDefFoundError: org/springframework/data/mongodb/repository/MongoRepository
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at com.example.demomongo.CustomerServices.get2(CustomerServices.java:28)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
>         at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:159)
>         at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$26(MSF4JMessageProcessor.java:86)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassNotFoundException: org.springframework.data.mongodb.repository.MongoRepository
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 22 more

picture error:
![44444444444444](https://user-images.githubusercontent.com/23513544/38477580-9e090b7c-3bdd-11e8-8e6b-e91dc4466200.PNG)

**Comment by thusithathilina** [comment]
Have you create the runnable jar with all the dependencies? If not are you having the relavent dependencies in your class path?

**Comment by hoabuiyt** [comment]
i using WSO2 MSF4J at **wso2ei-6.1.1-update17\wso2\msf4j\deployment\microservices**
and start msf4j of WSO at **wso2ei-6.1.1-update17\wso2\msf4j\bin** with command **carbon.bat**
build and deloy is successfull
and it ran normal with api simple
from line 16 at here https://github.com/hoabuiyt/DemoMongo/blob/master/src/main/java/com/example/demomongo/CustomerServices.java#L16
```
> @GET
> 	@Path("/get1")
>     public String get() {
>         System.out.println("GET 11111");
>         return "Test thanh cong !";
>     }
```

but when i call API with connector mongodb it show error
from here: https://github.com/hoabuiyt/DemoMongo/blob/master/src/main/java/com/example/demomongo/CustomerServices.java#L23

```
> @GET
> 	@Path("/get2")
> 	public Customer get2() {
> 		System.out.println("GET 22222");		
> 		try {
> 			repository.deleteAll();
> 
> 			// save a couple of customers
> 			repository.save(new Customer("Alice", "Smith"));
> 			repository.save(new Customer("Bob", "Smith"));
> 			
> 			// fetch an individual customer
> 			System.out.println("Customer found with findByFirstName('Alice'):");
> 			System.out.println("--------------------------------");
> 			System.out.println(repository.findByFirstName("Alice"));
> 			
> 			return repository.findByFirstName("Alice");
> 		} catch (Exception e) {
> 			// TODO: handle exception
> 			return null;
> 		}
>         
>     }
```

and this is my error: **WARN {org.wso2.msf4j.internal.MSF4JMessageProcessor} - Unmapped exception java.lang.NoClassDefFoundError: org/springframework/data/mongodb/repository/MongoRepository**

i think it wrong when connect to MongoDB and using WSO2 MSF4J

you can try my git https://github.com/hoabuiyt/DemoMongo.git

and please help me fix it

thank you @thusithathilina

**Comment by thusithathilina** [comment]
@hoabuiyt Are you packing the mongodb dependency class inside your deployable jar?

**Comment by hoabuiyt** [comment]
yes @thusithathilina 
this is my jar file
[DemoMongo-1.0.0.jar.zip](https://github.com/wso2/msf4j/files/1896906/DemoMongo-1.0.0.jar.zip)
